language: generic
env:
  global:
    - SWIFT_BRANCH=swift-4.2-branch
    - SWIFT_VERSION=swift-4.2-DEVELOPMENT-SNAPSHOT-2018-06-03-a
matrix:
  include:
    - script: swift package update && swift test
      os: osx
      osx_image: xcode9.4
      sudo: required
      install:
        - wget https://swift.org/builds/$SWIFT_BRANCH/xcode/$SWIFT_VERSION/$SWIFT_VERSION-osx.pkg
        - sudo installer -pkg $SWIFT_VERSION-osx.pkg -target /
        - export PATH="/Library/Developer/Toolchains/$SWIFT_VERSION.xctoolchain/usr/bin:$PATH"
    - script: swift package update && swift test
      os: linux
      sudo: required
      dist: trusty
      before_install:
        - sudo apt-get -qq update
        - sudo apt-get install -y libblocksruntime0
      install:
        - >
          curl https://swift.org/builds/$SWIFT_BRANCH/ubuntu1404/$SWIFT_VERSION/$SWIFT_VERSION-ubuntu14.04.tar.gz
          | tar xz --directory $HOME --strip-components=1
        - export PATH=$HOME/usr/bin:$PATH
