language: generic
env:
  global:
    - SWIFT_BRANCH=swift-5.0-release
    - SWIFT_VERSION=swift-5.0-RELEASE
matrix:
  include:
    - script: swift package update && swift test
      os: osx
      osx_image: xcode10.2
    - script: swift package update && swift test
      os: linux
      sudo: required
      dist: xenial
      before_install:
        - sudo apt-get -qq update
        - sudo apt-get install -y libblocksruntime0
      install:
        - >
          curl https://swift.org/builds/$SWIFT_BRANCH/ubuntu1604/$SWIFT_VERSION/$SWIFT_VERSION-ubuntu16.04.tar.gz
          | tar xz --directory $HOME --strip-components=1
        - export PATH=$HOME/usr/bin:$PATH
