#if !canImport(ObjectiveC)
import XCTest

extension TrampolineTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__TrampolineTests = [
        ("testAckermann", testAckermann),
        ("testEvenOdd", testEvenOdd),
        ("testFlatMap", testFlatMap),
        ("testFlatMap2", testFlatMap2),
        ("testFlatMap3", testFlatMap3),
        ("testMap", testMap),
        ("testMap2", testMap2),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(TrampolineTests.__allTests__TrampolineTests),
    ]
}
#endif
